# src/services/ai_assets_service.py
import logging
from typing import List, Any
from src.services.storage_service import storage_service

logger = logging.getLogger(__name__)

class AiAssetsService:
    """
    Handles the extraction, download, and upload of file artifacts (images/plots)
    generated by the OpenAI Code Interpreter to AWS S3.
    """

    @staticmethod
    def handle_generated_files(client, response_obj, folder: str = "chat_assets") -> List[str]:
        """Scans the OpenAI response for generated files and uploads them."""
        uploaded_urls = []
        container_id = None
        
        cf_client = AiAssetsService._get_files_client(client)
        if not cf_client: return []

        try:
            output_items = getattr(response_obj, "output", []) or []
            for item in output_items:
                item_type = getattr(item, "type", "")
                
                # Detect Container ID
                if item_type == "code_interpreter_call":
                    cid = getattr(item, "container_id", None) or \
                          (getattr(item.code_interpreter, "container_id", None) if hasattr(item, "code_interpreter") else None) or \
                          (getattr(item.code_interpreter_call, "container_id", None) if hasattr(item, "code_interpreter_call") else None)
                    if cid: container_id = cid

                # Detect File Citations
                if item_type == "message":
                    content_list = getattr(item, "content", []) or []
                    if isinstance(content_list, list):
                        for part in content_list:
                            annotations = getattr(part, "annotations", []) or []
                            for ann in annotations:
                                if getattr(ann, "type", "") == "container_file_citation":
                                    file_id = getattr(ann, "file_id", None)
                                    fname = getattr(ann, "filename", "graph.png")
                                    if file_id: 
                                        AiAssetsService._process_file(cf_client, container_id, file_id, fname, uploaded_urls, folder)

            # Fallback: List files in container if ID exists but no specific citation found
            if not uploaded_urls and container_id:
                try:
                    container_files = cf_client.list(container_id)
                    for c_file in container_files:
                        fname = getattr(c_file, "filename", None) or getattr(c_file, "name", None)
                        fid = getattr(c_file, "id", None) or getattr(c_file, "file_id", None)
                        if not fname: fname = "generated_plot.png"
                        if fid: 
                            AiAssetsService._process_file(cf_client, container_id, fid, fname, uploaded_urls, folder)
                except Exception: pass
        except Exception: pass
        return uploaded_urls

    @staticmethod
    def _get_files_client(client):
        """Locates the container files accessor in the OpenAI client."""
        if hasattr(client, "beta"):
            if hasattr(client.beta, "containers") and hasattr(client.beta.containers, "files"):
                return getattr(client.beta.containers, "files")
            if hasattr(client.beta, "container_files"):
                return getattr(client.beta, "container_files")
        if hasattr(client, "containers") and hasattr(client.containers, "files"):
            return getattr(client.containers, "files")
        return getattr(client, "container_files", None)

    @staticmethod
    def _process_file(cf_client, container_id, file_id, filename, url_list, folder: str):
        """Downloads content from OpenAI and uploads to AWS S3."""
        try:
            file_content = None
            if hasattr(cf_client, "content") and hasattr(cf_client.content, "retrieve"):
                try:
                    if container_id: file_content = cf_client.content.retrieve(container_id=container_id, file_id=file_id)
                    else: file_content = cf_client.content.retrieve(file_id=file_id)
                except: pass
                
            if file_content is None and callable(getattr(cf_client, "content", None)):
                try: file_content = cf_client.content(file_id)
                except: pass

            if not file_content: return

            if hasattr(file_content, "read"): file_content = file_content.read()
            elif hasattr(file_content, "content"): file_content = file_content.content
            elif hasattr(file_content, "text"): file_content = file_content.text.encode('utf-8')

            if not isinstance(file_content, (bytes, bytearray)):
                try: file_content = bytes(file_content)
                except: pass

            fname = str(filename).lower()
            if fname.endswith(".jpg") or fname.endswith(".jpeg"): ctype = "image/jpeg"
            elif fname.endswith(".pdf"): ctype = "application/pdf"
            else: 
                ctype = "image/png"
                if not fname.endswith(".png"): filename = f"{filename}.png"

            s3_url = storage_service.upload_image_from_bytes(file_content, ctype, folder=folder)
            logger.info(f"✅ Asset uploaded to S3: {s3_url}")
            url_list.append(s3_url)
        except Exception as e:
            logger.error(f"File transfer failed for {file_id}: {e}")

# Expose a simple singleton
ai_assets_service = AiAssetsService()