# src/schemas/quiz_schemas.py
from pydantic import BaseModel, Field
from typing import List, Optional

class QuizOption(BaseModel):
    # 🟢 FIX: Added explicit examples for numbers and \infty, and forced \\( \\) delimiters
    text: str = Field(..., description="The answer text. STRICT FORMATTING: EVERY single number, mathematical expression, equation, or symbol MUST be strictly wrapped in double-escaped inline LaTeX delimiters: \\\\( and \\\\). Example: instead of '0', output '\\\\( 0 \\\\)'. Instead of '-\\infty', output '\\\\( -\\\\infty \\\\)'. NEVER output plain text numbers or raw LaTeX for math options.")
    feedback: str = Field(..., description="Short feedback explaining why this option is right/wrong.")

class QuizQuestion(BaseModel):
    question_title: str = Field(..., description="Title with number, e.g., '# 1. Topic'")
    
    # -------------------------------------------------------------------------
    # LOGIC ENGINE: Preserved 'THE SETUP' for deep thinking
    # -------------------------------------------------------------------------
    explanation: str = Field(..., description=(
        "Detailed reasoning plan. YOU MUST FOLLOW THIS STRUCTURE:\n"
        "1. THE SETUP: Define the EXACT numbers/facts you will use.\n"
        "2. THE SOLUTION: Solve the problem step-by-step using ONLY the setup.\n"
        "3. THE TRAPS: Identify 3 failure paths based on these specifics."
    ))

    #  FIX: Also updated the question_text to provide the literal delimiter examples
    question_text: str = Field(..., description="The question stem. STRICT FORMATTING: Wrap ALL numbers, symbols, and math expressions in double-escaped LaTeX (\\\\( and \\\\)). You MUST double-escape every backslash. Example: '\\\\( -\\\\infty \\\\)' or '\\\\( 5 \\\\)'. MUST match 'THE SETUP' numbers exactly.")
    
    # EXISTING: Field for the Graph/Image URL
    image_url: Optional[str] = Field(None, description="URL of the generated image/graph. If you used the python tool to generate a graph, this will be populated.")

    # NEW: Weighted Scoring Logic
    difficulty: int = Field(1, ge=1, le=3, description="Difficulty weight: 1 (Basic/Easy), 2 (Application/Medium), 3 (Analysis/Hard).")

    options: List[QuizOption] = Field(..., min_items=4, max_items=4, description="Exactly 4 options.")
    correct_option_index: int = Field(..., ge=0, le=3, description="Index of the correct option (0-3).")

class QuizResponse(BaseModel):
    # NEW: Professional Title generated by AI
    title: str = Field(..., description="A professional, short, engaging title for this quiz based on the specific topic (Max 6 words).")
    intro_message: str = Field(..., description="A single, concise sentence introducing the quiz (Voice: Roma).")
    
    # NEW: Explicit question count for Frontend display
    question_count: int = Field(..., description="The total number of questions generated in this quiz.")
    
    questions: List[QuizQuestion]

    # NEW: Ghost Prompt Payloads (The "Next Steps")
    easier_payload: str = Field(..., description="A specific user command to generate an EASIER version of this quiz. E.g., 'Hazme un quiz más fácil sobre [Topic]'.")
    harder_payload: str = Field(..., description="A specific user command to generate a HARDER/ADVANCED version of this quiz. E.g., 'Hazme un examen avanzado sobre [Topic]'.")
    retry_payload: str = Field(..., description="A specific user command to generate a NEW quiz on the SAME TOPIC and SAME DIFFICULTY. E.g., 'Dame otro quiz sobre [Topic]'.")